Add event that is being fired upon the webhook's dispatch
spatie/laravel-webhook-server pull request #150
Opened 2023-11-26 11:16 UTC by thannaske

The idea for this PR came in regards of discussion #91, which introduced the idea of a database persistence layer. While this would be currently out of scope for this package, I figured that you could easily achieve everything the creator of the idea intended to do by utilising the package's events.

The only thing that was missing to allow persisting the webhook in whichever way the developer wants, was an event that is being fired exactly once when a new webhook is being dispatched (not to confuse with the dispatching of the job which could occur multiple times when retrying). For this reason, this PR adds the `WebhookCallDispatchedEvent` which fires when the `dispatch()` method for the `WebhookCall` object is being called.

One could then simply listen to the `WebhookCallDispatchedEvent`, persist it to the database and e.g. increase attempt counts or update the web hook's status based on fired `WebhookCallFailedEvent`s and `WebhookCallSucceededEvent`s.

I was unable to reuse the abstract `WebhookCallEvent` as it contains a lot of attributes that are specific to an actual attempt to send the webhook to its target URL.

Thank you for your work and of course no hard feelings if this PR is going to be declined.

2023-11-27 08:48 UTC, freekmurze requested changes

2023-11-27 11:42 UTC, thannaske commented on src/WebhookCall.php
> +        event(new WebhookCallDispatchedEvent(
Very good point, thank you. I amended the event's name and updated the `README.md` accordingly.

2023-11-27 11:45 UTC, merged

2024-08-08 09:11 UTC, siarheipashkevich commented
@thannaske which database structure of table did you use for storing handling outgoing webhooks?

2024-08-08 09:17 UTC, thannaske commented
@siarheipashkevich Please use GitHub's discussions for questions regarding the usage of the package, a (closed and over half a year old) Pull Request is not the right place for it.

You can however just put all available properties of the [DispatchingWebhookCallEvent](https://github.com/spatie/laravel-webhook-server/blob/main/src/Events/DispatchingWebhookCallEvent.php) into a table. The exact table structure depends on your individual needs.